# Generated by Django 2.1.3 on 2018-12-18 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20181218_1557'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disco',
        ),
    ]
