# Generated by Django 2.1.3 on 2018-12-18 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_delete_disco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'verbose_name_plural': 'Agencies'},
        ),
    ]
