# Generated by Django 2.1.3 on 2018-12-09 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MeteringStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_customers', models.PositiveIntegerField()),
                ('metered_customers', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('disco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Disco')),
            ],
            options={
                'verbose_name_plural': 'Metering Status',
            },
        ),
    ]
