# Generated by Django 2.1.3 on 2018-12-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_disco_meteringstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='disco',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
