# Generated by Django 2.1.5 on 2019-02-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_disco_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransmissionPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(0, 'Jan'), (1, 'Feb'), (2, 'Mar'), (3, 'Apr'), (4, 'May'), (5, 'Jun'), (6, 'Jul'), (7, 'Aug'), (8, 'Sep'), (9, 'Oct'), (10, 'Nov'), (11, 'Dec')])),
                ('year', models.IntegerField()),
                ('date', models.DateField()),
                ('disco_consumption', models.FloatField()),
                ('evacuated_energy', models.FloatField()),
                ('system_loss', models.FloatField()),
            ],
        ),
    ]
