# Generated by Django 2.1.5 on 2019-02-14 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_transmissionperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('disco_consumption', models.FloatField()),
                ('evacuated_energy', models.FloatField()),
                ('system_loss', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(0, 'Jan'), (1, 'Feb'), (2, 'Mar'), (3, 'Apr'), (4, 'May'), (5, 'Jun'), (6, 'Jul'), (7, 'Aug'), (8, 'Sep'), (9, 'Oct'), (10, 'Nov'), (11, 'Dec')])),
                ('year', models.IntegerField()),
                ('csv_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='TransmissionPerformance',
        ),
        migrations.AddField(
            model_name='performancedetail',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.PerformanceSummary'),
        ),
    ]
