# Generated by Django 2.1.5 on 2019-02-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20190214_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performancesummary',
            options={'verbose_name_plural': 'Performance Summary'},
        ),
        migrations.AddField(
            model_name='performancedetail',
            name='efficiency',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancedetail',
            name='inefficiency',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
