# Generated by Django 2.1.5 on 2019-02-15 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_auto_20190215_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='statspage',
            name='performance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stats.PerformanceSummary'),
        ),
    ]
