# Generated by Django 2.1.5 on 2019-02-15 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_auto_20190215_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hourly_generation', models.PositiveIntegerField()),
                ('daily_generation', models.PositiveIntegerField()),
                ('hourly_losses', models.PositiveIntegerField()),
                ('daily_losses', models.PositiveIntegerField()),
                ('constrained_value', models.DecimalField(decimal_places=5, max_digits=15)),
                ('peak_energy', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GenerationSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(0, 'Jan'), (1, 'Feb'), (2, 'Mar'), (3, 'Apr'), (4, 'May'), (5, 'Jun'), (6, 'Jul'), (7, 'Aug'), (8, 'Sep'), (9, 'Oct'), (10, 'Nov'), (11, 'Dec')])),
                ('year', models.IntegerField()),
                ('csv_file', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Generation Summary',
            },
        ),
        migrations.AddField(
            model_name='generationdetail',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.GenerationSummary'),
        ),
    ]
