# Generated by Django 2.1.5 on 2019-02-28 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0008_document_file_size'),
        ('stats', '0010_statspage_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='statspage',
            name='power_generation_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
