# Generated by Django 2.1.3 on 2019-01-03 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0040_page_draft_title'),
        ('training', '0003_auto_20181212_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', models.TextField(blank=True, null=True)),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RenameModel(
            old_name='ModulePage',
            new_name='LearningPage',
        ),
        migrations.RenameModel(
            old_name='ModuleSessionPage',
            new_name='LearningSessionPage',
        ),
        migrations.RemoveField(
            model_name='moduleindex',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='ModuleIndex',
        ),
    ]
