# Generated by Django 2.1.3 on 2019-01-03 11:59

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_auto_20190103_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningindex',
            name='audience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningindex',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningindex',
            name='instructor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='learningpage',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
