# Generated by Django 2.1.3 on 2019-01-05 13:39

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_learningpage_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
