# Generated by Django 2.1.5 on 2019-01-15 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_auto_20190115_0729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcqpage',
            old_name='intro',
            new_name='outline',
        ),
    ]
