# Generated by Django 2.1.5 on 2019-01-26 22:18

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpage',
            name='explanation',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
