# Generated by Django 2.1.5 on 2019-02-04 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('training', '0013_questionpage_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcqpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='MCQPage',
        ),
    ]
