# Generated by Django 2.1.5 on 2019-02-04 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0014_auto_20190204_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('examiner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
