# Generated by Django 2.1.5 on 2019-02-04 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0015_assignmentpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentpage',
            name='examiner',
        ),
        migrations.DeleteModel(
            name='AssignmentPage',
        ),
    ]
