# Generated by Django 2.1.5 on 2019-02-05 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0018_assignmentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentanswer',
            name='assignment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='training.AssignmentPage'),
            preserve_default=False,
        ),
    ]
