# Generated by Django 2.1.5 on 2019-02-05 08:22

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0019_assignmentanswer_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentanswer',
            name='answer',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
