# Generated by Django 2.1.5 on 2019-02-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0020_auto_20190205_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentanswer',
            name='assessed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='assignmentanswer',
            name='completed',
            field=models.DateTimeField(null=True),
        ),
    ]
