# Generated by Django 2.1.3 on 2018-12-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
