# Generated by Django 2.1.5 on 2019-03-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpage_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='author',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
