# Generated by Django 2.1.3 on 2018-12-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='intro',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
