# Generated by Django 2.1.5 on 2019-02-08 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0005_auto_20190208_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='top_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
