# Generated by Django 2.1.5 on 2019-02-28 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_metadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metadata',
            options={'verbose_name_plural': 'Metadata'},
        ),
    ]
